### ISSUE TITLE
Wrapper - HydPy Version check

### ISSUE THREAD

**Issue by GernotBelger** [hydpy-dev/OpenDA#3]
In order to enforce compatibility between the wrapper and hydpy, it would be nice to let the wrapper check the version of hydpy.
This could be achieved by fetching the version from the hydpy server e.g. by the status call.
However this would also require a fixed version number scheme.

**Comment by tyralla** [comment]
HydPy already uses a fixed version number scheme. It looks like "4.0.0" for releases and like "4.1a0" for pre-releases. Commit [3061536](https://github.com/hydpy-dev/hydpy/commit/3061536adb7d15411a291d6e2b6c61647c23b6f9) makes such a version string programmatically available via the module attribute `__version__` (see [PEP 396](https://www.python.org/dev/peps/pep-0396/)).

An official method to let the HydPy server return the version number is still missing.  A temporary solution is to use the general POST method "[evaluate](https://hydpy-dev.github.io/hydpy/master/servertools.html?highlight=post_evaluate#hydpy.exe.servertools.HydPyServer.POST_evaluate)" via sending the following string: `version = hydpy.__version__`

**Comment by tyralla** [comment]
While tidying up (squashing) our [feature/core/parallelisation](https://github.com/hydpy-dev/hydpy/tree/feature/exe%2Fservertools%2Fparallelisation) branch, I also added the "official" method `GET_get_version` in commit [252b5aa](https://github.com/hydpy-dev/hydpy/commit/252b5aae78fb2fa7365652a71fd4eb846b3bb3de).

Please note that `GET_status` is now `GET_get_status`.

**Comment by tyralla** [comment]
Two small fixes, and now Travis and AppVeyor do not complain anymore.  So I merged the `parallelisation` feature branch into `master` and removed it. 

4.1 will be the first version-aware HydPy release.

**Comment by GernotBelger** [comment]
I do not agreee with the renaqming of status and verison methods. Reason:  exetue and status where used in the path of the http-call; e.g. like http://localhost/execute?methods=xxx or http://localhost/status which at least looks like a restful interface (which actually it is not very much),
However now the calls look like https://localhost/get_status which makes it much uglier in my opinion. If you which to maintain these GET_ and POST_ named methods within the hydpy code, could could instead prefix them whithin the _do_get_or_post method.

**Comment by GernotBelger** [comment]
> An official method to let the HydPy server return the version number is still missing. A temporary solution is to use the general POST method "[evaluate](https://hydpy-dev.github.io/hydpy/master/servertools.html?highlight=post_evaluate#hydpy.exe.servertools.HydPyServer.POST_evaluate)" via sending the following string: `version = hydpy.__version__`

Actually this is a HUGE security issue if we would ever would use a HydPy Server instance between different servers / the internet. We should avoid something like that, where/why do we need this currently? I would definitely recommend remove that evaluate method.

**Comment by tyralla** [comment]
> 
> 
> > An official method to let the HydPy server return the version number is still missing. A temporary solution is to use the general POST method "[evaluate](https://hydpy-dev.github.io/hydpy/master/servertools.html?highlight=post_evaluate#hydpy.exe.servertools.HydPyServer.POST_evaluate)" via sending the following string: `version = hydpy.__version__`
> 
> Actually this is a HUGE security issue if we would ever would use a HydPy Server instance between different servers / the internet. We should avoid something like that, where/why do we need this currently? I would definitely recommend remove that evaluate method.

Yes, of course.  The HydPy Server is not supposed to be exposed to the internet.  If so, we would also need to re-work (many?) other things, starting from the chosen base classes (see these [Python docs](https://docs.python.org/library/http.server.html)).

So far, I see not see any use-case for which such security-considerations would be relevant. However, adding a warning note into our documentation similar to the one in the mentioned Python doc seems advisable.

I use the `evaluate` method for testing and debugging. So one option would be to add a "debug flag" when starting the server, which enables/disables this method.

**Comment by tyralla** [comment]
Lest we forget: we decided to use the "debug flag" for enabling/disabling the `evaluate` method (default=disabled).

**Comment by tyralla** [comment]
> 
> 
> I do not agreee with the renaqming of status and verison methods. Reason: exetue and status where used in the path of the http-call; e.g. like http://localhost/execute?methods=xxx or http://localhost/status which at least looks like a restful interface (which actually it is not very much),
> However now the calls look like https://localhost/get_status which makes it much uglier in my opinion. If you which to maintain these GET_ and POST_ named methods within the hydpy code, could could instead prefix them whithin the _do_get_or_post method.

No, the reason was consistency with other methods (e.g. `query_itemtypes`).  You could also send `get_status` and `get_version` as parameters to the GET method `execute`. But If "get" is ugly wording in this context, we can remove it, of course.
